# Generated by Django 5.0.1 on 2024-02-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="is_admin",
        ),
    ]
