# Generated by Django 5.0.1 on 2024-02-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_baseuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="admin"),
        ),
    ]
