# Generated by Django 5.0.2 on 2024-02-12 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_courseenrollment_course_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="text",
            field=models.TextField(verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="exercise/", verbose_name="file"
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="text"),
        ),
        migrations.CreateModel(
            name="ExerciseSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="text")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exercise_submissions/",
                        verbose_name="file",
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(auto_now_add=True, verbose_name="submission_date"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="course.exercise",
                        verbose_name="exercise",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
        ),
    ]
